name = "portfolio"
main = "worker.js"
compatibility_date = "2024-01-01"

routes = [
  "portfolio.tkurmann.ch/*",
  "www.tkurmann.ch/*"
]

[site]
bucket = "."
include = [
  "index.html",
  "projects.html",
  "publications.html",
  "resume.html",
  "css/**",
  "js/**",
  "data/**",
  "plans/**",
  "package.json"
]
exclude = ["worker.js", "wrangler.toml"]
